Fixed some typos in Readme
eslachance/enmap pull request #87
Opened 2021-11-10 23:20 UTC by austr1an

Some little enhancements I found in the readme. It's not a lot, but I'm perfectionist :)

2021-11-10 23:28 UTC, RealShadowNova requested changes

2021-11-10 23:28 UTC, RealShadowNova commented on README.md
> +The more data you have, the more complex it is, the more memory it will use. You can use the
```suggestion
The more data you have, the more complex it is, the more memory it may use. You can use the
```

2021-11-10 23:41 UTC, austr1an commented on README.md
> +The more data you have, the more complex it is, the more memory it will use. You can use the
Yeah it looks better

2021-11-11 00:12 UTC, eslachance approved these changes
Awesome, thanks for the fixes!

2021-11-11 00:12 UTC, merged